export const FETCH_ALL_PROFS_REQUEST = 'FETCH_ALL_PROFS_REQUEST';
export const FETCH_ALL_PROFS_SUCCESS = 'FETCH_ALL_PROFS_SUCCESS';
export const FETCH_ALL_PROFS_FAILURE = 'FETCH_ALL_PROFS_FAILURE';

export const FETCH_PROF_BY_ID_REQUEST = 'FETCH_PROF_BY_ID_REQUEST';
export const FETCH_PROF_BY_ID_SUCCESS = 'FETCH_PROF_BY_ID_SUCCESS';
export const FETCH_PROF_BY_ID_FAILURE = 'FETCH_PROF_BY_ID_FAILURE';
